name: Check for updates
on:
  schedule:
    - cron: '0 14 * * 1'
  workflow_dispatch: {}
jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'flathub'
    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: flathubbot
          GIT_COMMITTER_NAME: flathubbot
          GIT_AUTHOR_EMAIL: sysadmin@flathub.org
          GIT_COMMITTER_EMAIL: sysadmin@flathub.org
          EMAIL: sysadmin@flathub.org
          GITHUB_TOKEN: ${{ secrets.FP_BUILDER_FLATHUBBOT_TOKEN }}
        with:
          args: --update --never-fork org.flatpak.Builder.BaseApp.json
